### PR TITLE
remove gulp-util

### PR DESCRIPTION
**Pull request by kuangyeheng**
remove gulp-util

### CODE REVIEW

**Comment by iegik** [comment]
https://github.com/peter-vilja/gulp-clean/issues/28

**Comment by kuangyeheng** [comment]
The author seems to have stopped maintenance, i have fork one and publish to npm,  
You can use `npm i --save-dev clean` instead. @iegik

**Comment by kuangyeheng** [comment]
The author seems to have stopped maintenance, i have fork one and publish to npm,
You can use npm i --save-dev gulp-clean-fix instead. @iegik

**Comment by kuangyeheng** [comment]
The author seems to have stopped maintenance, i have fork one and publish to npm,
You can use `npm i --save-dev gulp-clean-fix` instead. @iegik

**Comment by peter-vilja** [comment]
Nice work! Sorry I have been rather inactive with this plugin as the gulp community has been rather against this kind of a plugin and advices to delete files and directories differently.

Anyways your changes look good. I'll publish a new version soon.
Thanks for your contribution 👍

**Comment by peter-vilja** [comment]
Published 0.4.0

**Pull request merged**
